name: one-off-store-features
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/one-off-store-features.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo temporary-runner-ok
